networks:
    video-library:
        driver: bridge

services:
    db:
        image: postgres:16.1-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgresSecret
            - POSTGRES_DB=video-database
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - '5432:5432'
        volumes:
            - .my_postgres_data:/var/lib/postgresql/data
    minio:
        command: server /data
        container_name: minio
        environment:
            - MINIO_ROOT_USER=root
            - MINIO_ROOT_PASSWORD=rootroot
        image: minio/minio
        ports:
            - '9000:9000'
        restart: unless-stopped
        volumes:
            - .s3:/data
    createBucket:
        container_name: createBucket
        depends_on:
            - minio
        entrypoint: bin/sh -c "mc config host add minio http://minio:9000 root rootroot; mc mb minio/video-app-files || exit 0"
        image: minio/mc