version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresSecret
      - POSTGRES_DB=video-database
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
      - .my_postgres_data:/var/lib/postgresql/data 
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
    